version: '2'

services:
  docker-lap7-deb:
    build: .
    image: docker-lap7-deb:1.1
    container_name: docker-lap7-deb
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /home/luis/www/html:/var/www/html
      - /home/luis/www/ssl:/etc/apache2/ssl
      - /home/luis/www/sites-enabled:/etc/apache2/sites-enabled
    extra_hosts:
      - "www.local:127.0.0.1"

